services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data

  prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
